### ISSUE TITLE
pop error message

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#683] opened 2018-12-03 18:54 UTC
![image](https://user-images.githubusercontent.com/25951555/49394819-c0cbbf00-f72c-11e8-97a8-d5f6dc402a6d.png)

Pop up coming 5 times when opening REACH on landing page or event page. Edge browser

**Comment by matthewberryman** [comment] 2018-12-03 20:32
duplicate of https://github.com/MSFREACH/msf-reach/issues/571

**Closed by matthewberryman** 2018-12-03 20:32 UTC
Labels: bug
