### ISSUE TITLE
Offline features for reporting

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#442] opened 2018-05-23 16:43 UTC
to sync the report once you get Internet connection

**Comment by matthewberryman** [comment] 2018-05-23 22:39
dupe of #336

**Closed by matthewberryman** 2018-05-23 22:39 UTC

**Comment by matthewberryman** [comment] 2018-05-23 22:41
(sorry tagged wrong issue), have updated my comment here although any email notification of my previous comment will have wrong link
