### ISSUE TITLE
Contacts, missions gathered under number (according to zoom out and in)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#354] opened 2018-04-04 14:22 UTC
![image](https://user-images.githubusercontent.com/25951555/38313431-ec63c1a6-381b-11e8-899e-209b64d83ddb.png)

**Comment by matthewberryman** [comment] 2018-04-05 03:17
duplicate of https://github.com/MSFREACH/msf-reach/issues/339

**Comment by matthewberryman** [comment] 2018-04-25 13:13
Per discussions today seems changes to respond to [previous comment](https://github.com/MSFREACH/msf-reach/issues/354#issuecomment-379822847) have gone in the wrong direction.

**Closed** 2018-05-18 02:40 UTC
Labels: bug
