### ISSUE TITLE
Report category

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#472] opened 2018-06-03 08:52 UTC
- remove 'contact' category as people can add contact by themselves on the platform
- put 'information' instead.

**Comment by matthewberryman** [comment] 2018-06-03 09:00
duplicate of https://github.com/MSFREACH/msf-reach/issues/465 and https://github.com/MSFREACH/msf-reach/issues/267#issuecomment-390607715

**Closed by matthewberryman** 2018-06-03 09:00 UTC
