### ISSUE TITLE
icon not linked to this RSS source (PWTC)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#353] opened 2018-04-04 13:54 UTC
![image](https://user-images.githubusercontent.com/25951555/38311849-0f56c950-3818-11e8-9756-8906877d3abc.png)

**Comment by anexact** [comment] 2018-04-04 13:54
Note that the image above contains two different RSS feeds.

**Comment by matthewberryman** [comment] 2018-05-18 04:41
As @anexact said this is a situation with overlap (thus mostly a dupe of https://github.com/MSFREACH/msf-reach/issues/128 ) and combined with a situation where there's also a lack of easily extractable information from one of the RSS feeds that would allow us to assign an icon.

**Comment by matthewberryman** [comment] 2018-05-21 03:54
closed per comments in #128 and here

**Comment by LucieGueuning** [comment] 2018-05-21 09:40
![image](https://user-images.githubusercontent.com/25951555/40301231-5aa13aae-5ce3-11e8-9ea4-0be072998ff6.png)

We do not have RSS feed anymore

**Comment by matthewberryman** [comment] 2018-05-21 09:46
REMINDER: please open new features and new bugs in separate issues, not in comments.

**Comment by matthewberryman** [comment] 2018-05-22 07:32
Make another icon similar to existing set with circle in middle instead of event type picture (?)
@anexact

**Comment by matthewberryman** [comment] 2018-05-29 00:10
also adding storm and high wind (PDC) warnings, fix other bugs preventing earthquake and tsunami from showing (without colour for level as not present in other data)

**Comment by matthewberryman** [comment] 2018-05-31 02:47
Noting bcbb0a2 and 5c273e1 were actually for #433 but doesn't seem worth it to rewrite git history

**Closed** 2018-05-31 02:48 UTC
Labels: bug
