### ISSUE TITLE
Vertical column on the right to be displayed as a box

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#369] opened 2018-04-10 13:19 UTC
@anexact to make it clear for MB

![image](https://user-images.githubusercontent.com/25951555/38559135-1e0bebb8-3cca-11e8-9874-80a3b74bbf7d.png)

**Comment by matthewberryman** [comment] 2018-04-16 23:39
dupe of #361 - @LucieGueuning if you have additional info to add on an existing issue please add comments

**Closed by matthewberryman** 2018-04-16 23:39 UTC
Labels: UX improvements
