### ISSUE TITLE
layers selection preferences are not memorise by the system on REACH

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#456] opened 2018-05-31 08:29 UTC
reported by Natasha on 31.05

**Comment by matthewberryman** [comment] 2018-05-31 08:53
I just tested them again then on dev site and couldn't reproduce. Which layers are affected, what is current browser?

**Comment by LucieGueuning** [comment] 2018-05-31 13:56
She is on her mac and layers that are always on even though she is putting them off is: contact, ongoing MSF projects, reports.

**Comment by matthewberryman** [comment] 2018-05-31 21:06
I tested those again and can't reproduce. Still awaiting feedback on which browser.

**Comment by matthewberryman** [comment] 2018-07-05 22:31
Closing; no further feedback and I can't reproduce.

**Closed by matthewberryman** 2018-07-05 22:31 UTC
Labels: bug
