### ISSUE TITLE
AI/ML

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#246] opened 2018-02-13 09:28 UTC
As per our discussion, two developments: 
1. Fake data on dev side to showcase how AI/ML can work with proper data (input fake data) to make life easier. System need to learn from data. Right suggestion of suppliers, what was the response in the past if ....
2. On landing page, on prod side, pop window with security items. 
3. @lucie : in addition to that, need to find more data regarding past responses.

**Comment by matthewberryman** [comment] 2018-02-13 21:49
Duplicate of 
https://github.com/MSFREACH/msf-reach/issues/182
https://github.com/MSFREACH/msf-reach/issues/165
https://github.com/MSFREACH/msf-reach/issues/89
https://github.com/MSFREACH/msf-reach/issues/32
I'll put the comments here pertaining to mission planning on the relevant issue.

**Closed by matthewberryman** 2018-02-13 21:49 UTC
