### ISSUE TITLE
free test box on report should not be limited (to a certain number of character)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#540] opened 2018-07-25 08:40 UTC

**Comment by matthewberryman** [comment] 2018-07-25 08:52
This is not a bug but would be a change in a design decision. We limited the number of characters (we could change the limit but see point 2 on display) as:
1. It's geared towards mobile as requested, and thus we don't have the space to make the box larger. If we allowed unlimited text then the user could enter more text than fits in the box all at once, which makes review and possible editing hard.
2. It means the issue of fit of text in the table and popups #541 becomes worse.

**Comment by anexact** [comment] 2018-07-25 17:18
Agree with @matthewberryman -- the idea is fine but the implications make it worse. Again, need to think through the issues before posting them as having been decided.

**Comment by LucieGueuning** [comment] 2018-08-14 14:33
@anexact How to ensure long report can be submitted?

**Comment by qclin** [comment] 2018-08-14 14:34
@LucieGueuning can you test on dev, and see if you get long report after submitting on landing page

**Comment by matthewberryman** [comment] 2018-08-15 00:35
@LucieGueuning I only just merged that into dev now (sorry for delay due to travel). Note that @qclin proposed some mechanisms for display of long reports - Qiao I have left that branch around if there's a need for any further tweaks around display.

**Comment by LucieGueuning** [comment] 2018-08-15 09:41
Working but display is not ok

![image](https://user-images.githubusercontent.com/25951555/44142303-b9213e8a-a077-11e8-9852-6d31aa869dd5.png)

**Comment by qclin** [comment] 2018-08-15 10:30
@LucieGueuning what do you mean, the line breaks or ?

**Comment by LucieGueuning** [comment] 2018-08-15 10:34
![image](https://user-images.githubusercontent.com/25951555/44144385-31d76186-a07f-11e8-9f91-76815eebdfe4.png)
@anexact to check and suggest solution from UI perspective.

**Comment by qclin** [comment] 2018-08-15 10:42
I see, the overflow should wrap, and selection label needs to be readable
anything else @LucieGueuning 
Please tell me exactly what you need improvement on as the highlight box on the display main text doesn't say anything, as I don't know when you enter whether there are line breaks or not.

**Comment by LucieGueuning** [comment] 2018-08-15 10:52
Yes, I think that'is all. I am not a UI designer by profession. So I am only seeing things as end users and I see that it is not readable. @anexact could help by suggesting something. But I think you covered the main issue with your comment up there. 

Thank you very much.

**Comment by qclin** [comment] 2018-08-15 10:53
@LucieGueuning got it, will resolve asap

**Comment by matthewberryman** [comment] 2018-08-24 21:59
@qclin how are we tracking on this and #541 ? When done, submit a PR that reads "fixes #541 fixes #541" so once it's merged into master it will auto-close.

**Closed** 2018-08-28 01:12 UTC
Labels: High Priority, question
