### ISSUE TITLE
Recording voice + uploading video on report card

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#338] opened 2018-03-21 16:50 UTC
Having the possibility of uploading a picture, **uploading a video** or **recording voice** on report card. 

Feature already mentioned during Phase 1 prototype. Again mentioned during one of our meeting this morning.

**Comment by matthewberryman** [comment] 2018-03-21 21:36
Duplicate of https://github.com/MSFREACH/msf-reach/issues/181

**Closed by matthewberryman** 2018-03-21 21:36 UTC
Labels: enhancement
