### ISSUE TITLE
re-open event 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#429] opened 2018-05-23 16:28 UTC
re-open event: from previous MSF Responses on landing page (modal or pop-up window)

**Comment by LucieGueuning** [comment] 2018-05-24 08:31
event mission history entered thanks to google spreadsheet at the very beginning

**Comment by matthewberryman** [comment] 2018-08-30 04:38
Duplicate of https://github.com/MSFREACH/msf-reach/issues/603

**Closed by matthewberryman** 2018-08-30 04:38 UTC
